/**
 * Property-based tests for PipeManager gap generation and Pipe entity
 *
 * Feature: flappy-bird-game, Property 5: pipe gaps always satisfy height constraints
 *
 * Validates: Requirements 3.2, 3.3
 */

// Feature: flappy-bird-game, Property 5: pipe gaps always satisfy height constraints

const fc = require('fast-check');
const { Pipe } = require('../pipe.js');
const { PipeManager } = require('../pipeManager.js');

describe('PipeManager — Property 5: pipe gaps always satisfy height constraints', () => {
  /**
   * **Validates: Requirements 3.2, 3.3**
   *
   * Property 5: For any pair of pipes generated by PipeManager:
   *   1. The top pipe height (gapY) is >= 50px (minPipeHeight)
   *   2. The bottom pipe height (canvasHeight - gapY - gapHeight) is >= 50px (minPipeHeight)
   *   3. The gap height is exactly 150px
   *   4. The initial X position of a spawned pipe equals canvasWidth (480)
   */

  const CANVAS_WIDTH = 480;
  const CANVAS_HEIGHT = 640;
  const GAP_HEIGHT = 150;
  const MIN_PIPE_HEIGHT = 50;

  test(
    '_calculateGapY always produces a gapY where top pipe height >= 50px',
    () => {
      fc.assert(
        fc.property(
          // Run many times to exercise the random gapY calculation
          fc.integer({ min: 0, max: 999999 }),
          (_seed) => {
            const manager = new PipeManager(CANVAS_WIDTH, CANVAS_HEIGHT);
            const gapY = manager._calculateGapY();

            // Top pipe height = gapY, must be >= minPipeHeight
            expect(gapY).toBeGreaterThanOrEqual(MIN_PIPE_HEIGHT);
          }
        ),
        { numRuns: 100 }
      );
    }
  );

  test(
    '_calculateGapY always produces a gapY where bottom pipe height >= 50px',
    () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 0, max: 999999 }),
          (_seed) => {
            const manager = new PipeManager(CANVAS_WIDTH, CANVAS_HEIGHT);
            const gapY = manager._calculateGapY();

            // Bottom pipe height = canvasHeight - gapY - gapHeight, must be >= minPipeHeight
            const bottomPipeHeight = CANVAS_HEIGHT - gapY - GAP_HEIGHT;
            expect(bottomPipeHeight).toBeGreaterThanOrEqual(MIN_PIPE_HEIGHT);
          }
        ),
        { numRuns: 100 }
      );
    }
  );

  test(
    'Pipe bounding boxes reflect correct gap height of exactly 150px for any valid gapY',
    () => {
      fc.assert(
        fc.property(
          // Generate valid gapY values: [minPipeHeight, canvasHeight - gapHeight - minPipeHeight]
          fc.integer({
            min: MIN_PIPE_HEIGHT,
            max: CANVAS_HEIGHT - GAP_HEIGHT - MIN_PIPE_HEIGHT,
          }),
          (gapY) => {
            const pipe = new Pipe(CANVAS_WIDTH, CANVAS_HEIGHT, gapY, GAP_HEIGHT, 60);

            const topBox = pipe.getBoundingBoxTop();
            const bottomBox = pipe.getBoundingBoxBottom();

            // Gap height = distance between bottom of top pipe and top of bottom pipe
            const actualGap = bottomBox.y - (topBox.y + topBox.height);
            expect(actualGap).toBe(GAP_HEIGHT);
          }
        ),
        { numRuns: 100 }
      );
    }
  );

  test(
    'Pipe bounding boxes reflect top pipe height >= 50px for any valid gapY',
    () => {
      fc.assert(
        fc.property(
          fc.integer({
            min: MIN_PIPE_HEIGHT,
            max: CANVAS_HEIGHT - GAP_HEIGHT - MIN_PIPE_HEIGHT,
          }),
          (gapY) => {
            const pipe = new Pipe(CANVAS_WIDTH, CANVAS_HEIGHT, gapY, GAP_HEIGHT, 60);
            const topBox = pipe.getBoundingBoxTop();

            expect(topBox.height).toBeGreaterThanOrEqual(MIN_PIPE_HEIGHT);
          }
        ),
        { numRuns: 100 }
      );
    }
  );

  test(
    'Pipe bounding boxes reflect bottom pipe height >= 50px for any valid gapY',
    () => {
      fc.assert(
        fc.property(
          fc.integer({
            min: MIN_PIPE_HEIGHT,
            max: CANVAS_HEIGHT - GAP_HEIGHT - MIN_PIPE_HEIGHT,
          }),
          (gapY) => {
            const pipe = new Pipe(CANVAS_WIDTH, CANVAS_HEIGHT, gapY, GAP_HEIGHT, 60);
            const bottomBox = pipe.getBoundingBoxBottom();

            expect(bottomBox.height).toBeGreaterThanOrEqual(MIN_PIPE_HEIGHT);
          }
        ),
        { numRuns: 100 }
      );
    }
  );

  test(
    'spawned pipes always have initial X position equal to canvasWidth (480)',
    () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 0, max: 999999 }),
          (_seed) => {
            const manager = new PipeManager(CANVAS_WIDTH, CANVAS_HEIGHT);

            // Force a spawn by advancing time past the spawn interval (1500ms)
            manager.update(1500);

            const pipes = manager.getPipes();
            expect(pipes.length).toBeGreaterThan(0);

            // The spawned pipe's x must equal canvasWidth
            const spawnedPipe = pipes[pipes.length - 1];
            expect(spawnedPipe.x).toBe(CANVAS_WIDTH);
          }
        ),
        { numRuns: 100 }
      );
    }
  );

  test(
    'all four constraints hold simultaneously for any valid gapY',
    () => {
      fc.assert(
        fc.property(
          fc.integer({
            min: MIN_PIPE_HEIGHT,
            max: CANVAS_HEIGHT - GAP_HEIGHT - MIN_PIPE_HEIGHT,
          }),
          (gapY) => {
            const pipe = new Pipe(CANVAS_WIDTH, CANVAS_HEIGHT, gapY, GAP_HEIGHT, 60);

            const topBox = pipe.getBoundingBoxTop();
            const bottomBox = pipe.getBoundingBoxBottom();

            // 1. Top pipe height >= minPipeHeight
            expect(topBox.height).toBeGreaterThanOrEqual(MIN_PIPE_HEIGHT);

            // 2. Bottom pipe height >= minPipeHeight
            expect(bottomBox.height).toBeGreaterThanOrEqual(MIN_PIPE_HEIGHT);

            // 3. Gap is exactly 150px
            const actualGap = bottomBox.y - (topBox.y + topBox.height);
            expect(actualGap).toBe(GAP_HEIGHT);

            // 4. Initial X position equals canvasWidth
            expect(pipe.x).toBe(CANVAS_WIDTH);
          }
        ),
        { numRuns: 100 }
      );
    }
  );
});
